language: node_js
node_js:
  - 8

script:
  - CI=true npm run build

deploy:
  provider: script
  script: "npm run deploy"
  skip_cleanup: true
  on:
    tags: true
    branch: master

notifications:
  email:
    recipients:
    - chris@unchained-capital.com
    on_success: change
    on_failure: always

before_deploy:
- git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- git config --global user.email "Travis CI<ci@unchained-capital.com>"
- git config --global user.name "TravisCI"

